# Generated by Django 4.1.6 on 2023-02-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo_dos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomPasajero', models.CharField(max_length=100)),
                ('ApePasajero', models.CharField(max_length=100)),
                ('DniPasajero', models.IntegerField()),
                ('FechaNacPas', models.DateField(null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Calle', models.CharField(max_length=100)),
                ('Nro', models.IntegerField()),
                ('Ciudad', models.CharField(max_length=100)),
                ('Provincia', models.CharField(max_length=100)),
                ('Pais', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField()),
                ('TitTarjeta', models.CharField(max_length=100)),
                ('NroTarjeta', models.IntegerField()),
                ('DniTit', models.IntegerField()),
                ('Vencimiento', models.DateField(null=True)),
                ('CVV', models.IntegerField()),
            ],
        ),
    ]
